name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set JAVA_HOME to JDK 17
      run: |
        echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true
        working-directory: android
        
    - name: Verify Java version
      run: java -version

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        ./gradlew clean
        bundle exec fastlane android firebase_distribution
      working-directory: android
